---
title: "Madden Summary"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(plyr)
library(tidytext)
library(tidyverse)
library(testthat)
library(DT)

##Functions

standard_mutate <- 
  function(x){
    round((x-mean(x, na.rm = T))/sd(x, na.rm = T),2)
  }

## Player data downloaded using EA Companion App and maddenexporter.com

player_data <- 
  read_csv("./input/players.csv") %>% 
  select(teamId, team, firstName, lastName, position, playerBestOvr, contractSalary, 
         contractBonus, contractLength, capHit, everything()) %>% 
  mutate(youth = pmin(pmax(0, 26-age)),3)


player_data$team[player_data$isOnPracticeSquad] <-"PRACTICE_SQUAD" 
player_data$team[is.na(player_data$team)] <-"FA" 


vec = c("QB",1, "RG",1, "LG", 1, "C", 1, "LT", 1, "RT", 1, "LE", 1, "RE", 1, "DT", 1, "LOLB", 1,
        "ROLB", 1, "MLB", 1, "SS", 2, "FS", 1, "CB", 2, "WR", 3, "TE", 1, "HB", 1, "K", 1, "P", 1)

required_depth <-  as_tibble(matrix(vec, ncol=2, byrow = T), .name_repair = "minimal") %>% set_names(nm = c("position", "num"))

group_positions <- 
  list(
    data.frame(group_position = "OL", position = c("RG","LG","C", "LT", "RT")),
    data.frame(group_position = "DL", position = c("LE", "RE", "DT")),
    data.frame(group_position = "LB", position = c("LOLB", "ROLB", "MLB")),
    data.frame(group_position = "DB", position = c("SS", "FS", "CB")),
    data.frame(group_position = "WR", position = c("WR")),
    data.frame(group_position = "TE", position = c("TE")),
    data.frame(group_position = "QB", position = c("QB")),
    data.frame(group_position = "RB", position = c("HB", "FB")),
    data.frame(group_position = "K", position = c("K","P"))
  )

group_positions_df <- bind_rows(group_positions)

##Quick test to make sure you've provided a map for all positions in data

testthat::expect_true(all(unique(player_data$position) %in% group_positions_df$position))

simple_positions <- 
  list(
    data.frame(simple_position = "Offense", group_position = c("OL", "WR", "TE", "RB", "QB") ),
    data.frame(simple_position = "Defense", group_position = c("DL", "LB", "DB")),
    data.frame(simple_position = "Special_Team", group_position = c("K"))
  )

simple_positions_df <- bind_rows(simple_positions)

##Quick test to make sure you've provided a map for all positions in data 

testthat::expect_true(all(unique(group_positions_df$group_position) %in% simple_positions_df$group_position))

player_data <- 
  player_data %>% 
  left_join(group_positions_df, by = "position") %>% 
  left_join(simple_positions_df, by = "group_position")

```


Draft
=====================================  

Sidebar {.sidebar}
-------------------------------------

```{r}


selectInput(inputId = "attributes_target_2_QB",
            label = "QB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            # selected = c("playerBestOvr", "youth", "devTrait", "throwAccDeepRating", 
            #              "throwAccMidRating", "throwAccRating", 
            #              "throwAccShortRating", "throwPowerRating", 
            #              "throwUnderPressureRating", "tightSpiralTrait"),
            selected = c("playerBestOvr", "youth", "devTrait", "throwAccShortRating", "throwAccDeepRating", 
                         "throwPowerRating",
                         "throwUnderPressureRating", "tightSpiralTrait"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_WR",
            label = "WR Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait", "speedRating", "jumpRating", 
                         "accelRating", "releaseRating", "catchRating", "routeRunShortRating", "routeRunDeepRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_TE",
            label = "TE Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait", "runBlockRating", "passBlockRating",
                         "playRecRating", "speedRating", "jumpRating", 
                         "accelRating", "releaseRating", "catchRating", "routeRunShortRating", "routeRunDeepRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_HB",
            label = "HB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait", "awareRating", "playRecRating", "bCVRating", "catchRating", "breakTackleRating", "speedRating", "accelRating", "passBlockRating",
                         "carryRating", "strengthRating", "jukeMoveRating", "truckRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_FB",
            label = "FB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "leadBlockRating", "awareRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_LE",
            label = "LE Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait", "blockShedRating", 
                         "awareRating", "playRecRating", "dLBullRushTrait",
                         "tackleRating", "pursuitRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_RE",
            label = "RE Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait", "blockShedRating", 
                         "awareRating", "playRecRating", "dLBullRushTrait",
                         "tackleRating", "pursuitRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_DT",
            label = "DT Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait", "blockShedRating", 
                         "awareRating", "playRecRating", "dLBullRushTrait",
                         "tackleRating", "pursuitRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_C",
            label = "C Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait",  "awareRating", 
                         "playRecRating", "passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_RG",
            label = "RG Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait",  "awareRating", 
                         "playRecRating", "passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_LG",
            label = "LG Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait",  "awareRating", 
                         "playRecRating", "passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_RT",
            label = "RT Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait",  "awareRating", 
                         "playRecRating", "passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_LT",
            label = "LT Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait",  "awareRating", 
                         "playRecRating", "passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_LOLB",
            label = "LOLB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected =c("playerBestOvr", "youth", "devTrait",  "awareRating", 
                        "playRecRating", "passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_ROLB",
            label = "ROLB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait", "awareRating", 
                         "playRecRating", "speedRating", "accelRating", 
                         "tackleRating", "pursuitRating", "zoneCoverRating", "manCoverRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_MLB",
            label = "MLB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait", "awareRating", "playRecRating", 
                         "speedRating", "accelRating", 
                         "tackleRating", "pursuitRating", "zoneCoverRating", "changeOfDirectionRating", "zoneCoverRating", "manCoverRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_CB",
            label = "CB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait", "awareRating", "playRecRating", 
                         "speedRating", "accelRating", "agility",
                         "manCoverRating", "catchRating", "playBallTrait", "zoneCoverRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_SS",
            label = "SS Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait", "awareRating", "playRecRating", 
                         "speedRating", "accelRating", 
                         "tackleRating", "pursuitRating", "zoneCoverRating",  "manCoverRating",
                         "catchRating", "playBallTrait", "changeOfDirectionRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_FS",
            label = "FS Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "youth", "devTrait", "awareRating", "playRecRating", 
                         "speedRating", "accelRating",   "manCoverRating",
                         "tackleRating", "pursuitRating", "zoneCoverRating", "catchRating", "playBallTrait",
                         "changeOfDirectionRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_P",
            label = "P Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("kickAccRating", "kickPowerRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_K",
            label = "K Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("kickAccRating", "kickPowerRating"),
            multiple = TRUE
)



df_adj <- structure(list(term = c("LOLB", "LT", "LE", "DT", "SS", "MLB", 
                                  "K", "RG", "TE", "ROLB", "LG", "WR", "FS", "CB", "HB", "P", "QB", 
                                  "RE", "RT", "C", "FB"), adjustment = c(0.862629912479771, 0.90910023267521, 
                                                                         0.929600934318827, 0.857455750288059, 0.804422695726924, 0.916405774674934, 
                                                                         0.399402386037169, 0.823656929607914, 0.810042189930614, 0.900599462830276, 
                                                                         0.852989137742854, 0.875878186217941, 0.858236691240959, 0.952873137803954, 
                                                                         0.818204105395157, 0.451785887708866, 1, 0.894419724590175, 0.886991503780299, 
                                                                         0.837555614337102, 0.745367603657523)), row.names = c(NA, -21L
                                                                         ), class = c("tbl_df", "tbl", "data.frame"))

#Came From This Code in a separate analysis
# cores <- parallel::detectCores()
# 
# player_data_numeric <- 
#   player_data_slim %>% 
#   # filter(position == i) %>% 
#   select_if(is.numeric) 
# 
# player_data_logic <- 
#   player_data_slim %>% 
#   # filter(position == i) %>% 
#   select_if(is.logical) %>%
#   mutate_if(is.logical, as.integer)
# 
# player_data_data_first <- 
#   player_data_slim %>% select(team:position) %>%  
#   cbind(player_data_numeric) %>% 
#   cbind(player_data_logic) %>% 
#   filter(yearsPro>4) %>%  
#   filter(yearsPro<8) %>%  
#   mutate(salary_per_year = contractSalary/contractLength) %>% 
#   filter(!is.na(salary_per_year)) %>% 
#   select(id, team, firstName, lastName, contractYearsLeft, salary_per_year, position , playerBestOvr, devTrait) 
# 
# player_data_data <- 
#   player_data_data_first %>% 
#   pivot_wider(names_from = "position", values_from = "playerBestOvr")
# 
# summary <- 
# player_data_data_first %>% 
#   mutate(player_type = ifelse((playerBestOvr>66) & (playerBestOvr<74), "low_player", NA)) %>% 
#   mutate(player_type = ifelse((playerBestOvr>76) & (playerBestOvr<84), "high_player", player_type)) %>% 
#   filter(!is.na(player_type)) %>% 
#   group_by(position, player_type) %>% 
#   summarise(salary_per_year = mean(salary_per_year)) %>% 
#   pivot_wider(names_from = "player_type", values_from = salary_per_year) %>% 
#   mutate(cost_per_pt = (high_player - low_player)/10)
#   
# 
# player_data_data[is.na(player_data_data)] <- 0
# 
# set.seed(123)
# splits      <- initial_split(player_data_data, strata = salary_per_year, prop = .90)
# 
# player_other <- training(splits)
# player_test  <- testing(splits)
# 
# set.seed(345)
# folds <- vfold_cv(player_other, v = 3)
# folds
# 
# # cores <- pmin(cores, 10)
# 
# model <-
#     linear_reg() %>%
#     set_mode("regression") %>%
#     set_engine("lm")
# 
# recipe <- 
#   recipe(salary_per_year ~ ., data = player_other) %>% 
#   # step_ns(playerBestOvr, deg_free = 2) %>%  #, 
#   update_role(id, team, firstName, lastName, contractYearsLeft, new_role = "ID") %>%
#   step_mutate(devTrait = as.factor(devTrait))
#   # step_dummy(position) #, devTrait) 
#  
# workflow <- 
#   workflow() %>% 
#   add_model(model) %>% 
#   add_recipe(recipe)
# 
# final_fit <- 
#   workflow %>%
#   fit(data = player_other) 
# 
# library(broom)
# df_adj <- tidy(final_fit$fit$fit)
# 
# df_adj$adjustment <- df_adj$estimate / (df_adj$estimate[df_adj$term=="QB"])
# 
# df_adj


player_data_slim_1 <- 
  player_data %>% 
  # filter(draftRound<56) %>% 
  mutate(salary_per_year = contractSalary/contractLength) %>% 
  mutate(id = as.character(id))

total_salary <- sum(player_data_slim_1$salary_per_year, na.rm = T)/2

player_data_value <- 
  player_data_slim_1 %>% 
  mutate(z_score = standard_mutate(playerBestOvr)) %>% 
  group_by(position) %>% 
  mutate(replacement = quantile(z_score, probs = .55)) %>% 
  mutate(zsar = z_score - replacement) %>% 
  mutate(salary_per_year = contractSalary/contractLength) %>% 
  ungroup() %>% 
  left_join(df_adj %>% select(term, adjustment), by = c("position"  = "term")) %>% 
  mutate(zsar_adj = zsar *adjustment) %>% 
  mutate(annual_value = round((total_salary/sum(zsar_adj, na.rm = T))*zsar_adj,0)) %>% 
  mutate(annual_excess_value = annual_value - salary_per_year) %>% 
  select(id, team, firstName, lastName, position, age, yearsPro, draftPick, draftRound, playerBestOvr, devTrait, 
         z_score, replacement, zsar, adjustment, zsar_adj,
         salary_per_year, contractYearsLeft,
         annual_value, annual_excess_value) %>% 
  mutate(adj_contract_years_left = pmin(pmax(30-age,1), contractYearsLeft)) %>% 
  mutate(total_value_contract = adj_contract_years_left * annual_excess_value) %>% 
  arrange(desc(total_value_contract))

##Expected Draft position
# draft_position <- 
#   player_data %>% 
#   filter(draftRound<56) %>% 
#   select(id, draftPick, draftRound) %>% 
#   mutate(expect_draft_pos = (draftRound-2)*32+(draftPick - 1),
#          id = as.character(id)) %>% 
#   select(-draftPick, -draftRound)


```

Draft Tables  {.tabset .tabset-fade}
-------------------------------------

### Draft Individual

```{r eval=T}


DT::renderDataTable({
  
  WR_chose_attr <-    input$attributes_target_2_WR
  QB_chose_attr <-    input$attributes_target_2_QB
  C_chose_attr <-     input$attributes_target_2_C
  HB_chose_attr <-    input$attributes_target_2_HB
  FB_chose_attr <-    input$attributes_target_2_FB
  CB_chose_attr <-    input$attributes_target_2_CB
  RE_chose_attr <-    input$attributes_target_2_RE
  RG_chose_attr <-    input$attributes_target_2_RG
  RT_chose_attr <-    input$attributes_target_2_RT
  LE_chose_attr <-    input$attributes_target_2_LE
  LG_chose_attr <-    input$attributes_target_2_LG
  LT_chose_attr <-    input$attributes_target_2_LT
  DT_chose_attr <-    input$attributes_target_2_DT
  LOLB_chose_attr <-  input$attributes_target_2_LOLB
  ROLB_chose_attr <-  input$attributes_target_2_ROLB
  SS_chose_attr <-    input$attributes_target_2_SS
  FS_chose_attr <-    input$attributes_target_2_FS
  TE_chose_attr <-    input$attributes_target_2_TE
  MLB_chose_attr <-   input$attributes_target_2_MLB
  P_chose_attr <-     input$attributes_target_2_P
  K_chose_attr <-     input$attributes_target_2_K
  
  # 
  #   WR_chose_attr <- c("playerBestOvr","speedRating","routeRunShortRating","runBlockFinesseRating","runBlockPowerRating" )
  #   QB_chose_attr <- c("playerBestOvr","speedRating")
  #   HB_chose_attr <- c("playerBestOvr")
  #   FB_chose_attr <- c("playerBestOvr", "elusiveRating", "jukeMoveRating")
  #   CB_chose_attr <- c("playerBestOvr","speedRating")
  #   RE_chose_attr <- c("playerBestOvr","speedRating")
  #   RG_chose_attr <- c("playerBestOvr","speedRating")
  #   RT_chose_attr <- c("playerBestOvr","speedRating")
  #   LE_chose_attr <- c("playerBestOvr","speedRating")
  #   LG_chose_attr <- c("playerBestOvr","speedRating")
  #   LT_chose_attr <- c("playerBestOvr","speedRating")
  #   DT_chose_attr <- c("playerBestOvr","speedRating")
  #   LOLB_chose_attr <- c("playerBestOvr","speedRating")
  #   ROLB_chose_attr <- c("playerBestOvr","speedRating")
  #   SS_chose_attr <- c("playerBestOvr","speedRating")
  #   FS_chose_attr <- c("playerBestOvr","speedRating")
  #   TE_chose_attr <- c("playerBestOvr","speedRating")
  #   MLB_chose_attr <- c("playerBestOvr","speedRating")
  #   C_chose_attr <- c("playerBestOvr","speedRating")
  #   P_chose_attr <- c("playerBestOvr","speedRating")
  #   K_chose_attr <- c("playerBestOvr","speedRating")
  
  attr_obj <- lst(
    WR_chose_attr ,  
    QB_chose_attr ,  
    C_chose_attr ,   
    HB_chose_attr ,  
    FB_chose_attr ,  
    CB_chose_attr ,  
    RE_chose_attr ,  
    RG_chose_attr ,  
    RT_chose_attr ,  
    LE_chose_attr ,  
    LG_chose_attr ,  
    LT_chose_attr ,  
    DT_chose_attr ,    
    LOLB_chose_attr ,  
    ROLB_chose_attr ,
    SS_chose_attr ,    
    FS_chose_attr ,    
    TE_chose_attr ,    
    MLB_chose_attr , 
    P_chose_attr ,     
    K_chose_attr,
  )
  
  df_attr <- plyr::ldply(attr_obj, rbind)
  df_attr <- gather(data = df_attr, key = key, value = value, na.rm = T, -.id)
  
  df_attr <- 
    df_attr %>% 
    select(-key) %>% 
    rename(key = .id)
  
  df_attr <- df_attr %>% mutate(key = gsub(pattern = "_chose_attr",replacement = "", x = .[["key"]]))
  
  df_attr$use = 1
  
  df_attr <- 
    df_attr %>%
    rename(position = key,
           attribute = value)
  
  df_initial <- 
    player_data_slim_1 %>% 
    # filter(draftRound<56) %>% 
    ungroup() %>% 
    # group_by(position) %>% 
    mutate_if(is.numeric, .funs = standard_mutate) %>% 
    gather(key = "attribute", "value", -id, -team, -firstName, -lastName, -position) %>% 
    left_join(df_attr) %>% 
    filter(use == 1) %>% 
    filter(!is.na(use)) %>% 
    mutate(id = as.character(id)) %>% 
    group_by(id, team, firstName, lastName, position) %>% 
    mutate(value = round(as.numeric(value),3)) %>% 
    summarise(value = round(mean(value, na.rm = T),3)) %>% 
    arrange(desc(value))
  
  
  player_data_value_2 <- 
    df_initial %>% 
    ungroup() %>% 
    mutate(z_score_2 = standard_mutate(value)) %>% 
    group_by(position) %>% 
    mutate(replacement_2 = quantile(z_score_2, probs = .5)) %>% 
    mutate(zsar_2 = z_score_2 - replacement_2) %>% 
    ungroup() %>% 
    left_join(df_adj %>% select(term, adjustment), by = c("position"  = "term")) %>% 
    mutate(zsar_adj_2 = zsar_2 *adjustment) %>% 
    mutate(annual_value_pick = round((total_salary/sum(zsar_adj_2, na.rm = T))*zsar_adj_2,0)) %>% 
    select(id:position, z_score_2, zsar_2, zsar_adj_2, annual_value_pick)
  
  player_data_value_final <- 
    player_data_value %>% left_join(player_data_value_2) %>% 
    mutate(annual_excess_value_pick = round(annual_value_pick - salary_per_year,0), 
           total_value_contract_pick = adj_contract_years_left * annual_excess_value_pick) %>% 
    arrange(desc(total_value_contract_pick))# %>% 
  # left_join(draft_position) %>% 
  # mutate(actual_value_pos = rank(desc(total_value_contract_pick))) %>% 
  # mutate(value_pick = -(actual_value_pos-expect_draft_pos))
  
  
  DT::datatable(player_data_value_final, extensions = c('Buttons','FixedColumns'),
                filter = "top",
                options = list(
                  scrollX = TRUE,
                  pageLength = -1, 
                  scrollY = "600px",
                  fixedColumns = list(leftColumns = 5), 
                  dom = 'Bfrti',
                  buttons = list(
                    list(extend = 'collection',
                         buttons = c('excel', 'csv'),
                         text = 'DOWNLOAD DATA')
                  ))) 
})


```


### Draft Team

```{r eval=T}


DT::renderDataTable({
  
  WR_chose_attr <-    input$attributes_target_2_WR
  QB_chose_attr <-    input$attributes_target_2_QB
  C_chose_attr <-     input$attributes_target_2_C
  HB_chose_attr <-    input$attributes_target_2_HB
  FB_chose_attr <-    input$attributes_target_2_FB
  CB_chose_attr <-    input$attributes_target_2_CB
  RE_chose_attr <-    input$attributes_target_2_RE
  RG_chose_attr <-    input$attributes_target_2_RG
  RT_chose_attr <-    input$attributes_target_2_RT
  LE_chose_attr <-    input$attributes_target_2_LE
  LG_chose_attr <-    input$attributes_target_2_LG
  LT_chose_attr <-    input$attributes_target_2_LT
  DT_chose_attr <-    input$attributes_target_2_DT
  LOLB_chose_attr <-  input$attributes_target_2_LOLB
  ROLB_chose_attr <-  input$attributes_target_2_ROLB
  SS_chose_attr <-    input$attributes_target_2_SS
  FS_chose_attr <-    input$attributes_target_2_FS
  TE_chose_attr <-    input$attributes_target_2_TE
  MLB_chose_attr <-   input$attributes_target_2_MLB
  P_chose_attr <-     input$attributes_target_2_P
  K_chose_attr <-     input$attributes_target_2_K
  
  
  # WR_chose_attr <- c("playerBestOvr","speedRating","routeRunShortRating","runBlockFinesseRating","runBlockPowerRating" )
  # QB_chose_attr <- c("playerBestOvr","speedRating")
  # HB_chose_attr <- c("playerBestOvr")
  # FB_chose_attr <- c("playerBestOvr", "elusiveRating", "jukeMoveRating")
  # CB_chose_attr <- c("playerBestOvr","speedRating")
  # RE_chose_attr <- c("playerBestOvr","speedRating")
  # RG_chose_attr <- c("playerBestOvr","speedRating")
  # RT_chose_attr <- c("playerBestOvr","speedRating")
  # LE_chose_attr <- c("playerBestOvr","speedRating")
  # LG_chose_attr <- c("playerBestOvr","speedRating")
  # LT_chose_attr <- c("playerBestOvr","speedRating")
  # DT_chose_attr <- c("playerBestOvr","speedRating")
  # LOLB_chose_attr <- c("playerBestOvr","speedRating")
  # ROLB_chose_attr <- c("playerBestOvr","speedRating")
  # SS_chose_attr <- c("playerBestOvr","speedRating")
  # FS_chose_attr <- c("playerBestOvr","speedRating")
  # TE_chose_attr <- c("playerBestOvr","speedRating")
  # MLB_chose_attr <- c("playerBestOvr","speedRating")
  # C_chose_attr <- c("playerBestOvr","speedRating")
  # P_chose_attr <- c("playerBestOvr","speedRating")
  # K_chose_attr <- c("playerBestOvr","speedRating")
  
  attr_obj <- lst(
    WR_chose_attr ,  
    QB_chose_attr ,  
    C_chose_attr ,   
    HB_chose_attr ,  
    FB_chose_attr ,  
    CB_chose_attr ,  
    RE_chose_attr ,  
    RG_chose_attr ,  
    RT_chose_attr ,  
    LE_chose_attr ,  
    LG_chose_attr ,  
    LT_chose_attr ,  
    DT_chose_attr ,    
    LOLB_chose_attr ,  
    ROLB_chose_attr ,
    SS_chose_attr ,    
    FS_chose_attr ,    
    TE_chose_attr ,    
    MLB_chose_attr , 
    P_chose_attr ,     
    K_chose_attr,
  )
  
  df_attr <- plyr::ldply(attr_obj, rbind)
  df_attr <- gather(data = df_attr, key = key, value = value, na.rm = T, -.id)
  
  df_attr <- 
    df_attr %>% 
    select(-key) %>% 
    rename(key = .id)
  
  df_attr <- df_attr %>% mutate(key = gsub(pattern = "_chose_attr",replacement = "", x = .[["key"]]))
  
  df_attr$use = 1
  
  df_attr <- 
    df_attr %>%
    rename(position = key,
           attribute = value)
  
  df_initial <- 
    player_data_slim_1 %>% 
    # filter(draftRound<56) %>% 
    ungroup() %>% 
    # group_by(position) %>% 
    mutate_if(is.numeric, .funs = standard_mutate) %>% 
    gather(key = "attribute", "value", -id, -team, -firstName, -lastName, -position) %>% 
    left_join(df_attr) %>% 
    filter(use == 1) %>% 
    filter(!is.na(use)) %>% 
    mutate(id = as.character(id)) %>% 
    group_by(id, team, firstName, lastName, position) %>% 
    mutate(value = as.numeric(value)) %>% 
    summarise(value = mean(value, na.rm = T)) %>% 
    arrange(desc(value))
  
  
  player_data_value_2 <- 
    df_initial %>% 
    ungroup() %>% 
    mutate(z_score = standard_mutate(value)) %>% 
    group_by(position) %>% 
    mutate(replacement = quantile(z_score, probs = .5)) %>% 
    mutate(zsar = z_score - replacement) %>% 
    ungroup() %>% 
    left_join(df_adj %>% select(term, adjustment), by = c("position"  = "term")) %>% 
    mutate(zsar_adj = zsar *adjustment) %>% 
    mutate(annual_value_pick = (total_salary/sum(zsar_adj, na.rm = T))*zsar_adj) %>% 
    select(id:position, annual_value_pick)
  
  player_data_value_final_team <- 
    player_data_value %>% left_join(player_data_value_2) %>% 
    mutate(annual_excess_value_pick = annual_value_pick - salary_per_year, 
           total_value_contract_pick = adj_contract_years_left * annual_excess_value_pick) %>% 
    arrange(desc(total_value_contract_pick)) %>% 
    # left_join(draft_position) %>% 
    # mutate(actual_value_pos = rank(desc(total_value_contract_pick))) %>% 
    # mutate(value_pick = -(actual_value_pos-expect_draft_pos)) %>% 
    left_join(required_depth) %>% 
    arrange(desc(total_value_contract_pick)) %>% 
    group_by(team, position) %>% 
    mutate(rank = rank(desc(annual_value_pick), ties.method = "first")) %>% 
    filter(rank <= num) %>%
    summarise(value = round(mean(total_value_contract_pick),0)) %>%
    spread(key = position, value = value, fill = -1000000) %>%
    mutate(Total = C+ CB+ DT+ FS+ HB+ K+ LE+ LG+ LOLB+ LT+ MLB+ P+ QB+ RE+ RG+ ROLB+ RT+ SS+ TE+ WR) %>%
    mutate(Brent_Total = (1*C+ 2*CB+ 2*DT+ 2*FS+ 1*HB+ .5*K+ 2*LE+ 
                            1*LG+ 2*LOLB+ 1*LT+ 1*MLB+ .5*P+ 2*QB+ 2*RE+ 1*RG+ 
                            2*ROLB+ 1*RT+ 2*SS+ 1*TE+ 2*WR)/
             sum(1,2,2,2,1,.5,2,1,2,1,1,.5,2,2,1,2,1,2,2,2)
           
    ) %>%
    arrange(desc(Brent_Total))
  
  
  DT::datatable(player_data_value_final_team, extensions = c('Buttons','FixedColumns'),
                filter = "top",
                options = list(
                  scrollX = TRUE,
                  pageLength = -1, 
                  scrollY = "600px",
                  fixedColumns = list(leftColumns = 1), 
                  dom = 'Bfrti',
                  buttons = list(
                    list(extend = 'collection',
                         buttons = c('excel', 'csv'),
                         text = 'DOWNLOAD DATA')
                  ))) %>% 
    formatCurrency(columns = ~C+ CB+ DT+ FS+ HB+ K+ LE+ LG+ LOLB+ LT+ MLB+ P+ QB+ RE+ RG+ ROLB+ RT+ SS+ TE+ WR + Total+Brent_Total,
                   digits = 0)
})


```

### Draft Team (Tranpose)

```{r eval=T}


DT::renderDataTable({
  
  WR_chose_attr <-    input$attributes_target_2_WR
  QB_chose_attr <-    input$attributes_target_2_QB
  C_chose_attr <-     input$attributes_target_2_C
  HB_chose_attr <-    input$attributes_target_2_HB
  FB_chose_attr <-    input$attributes_target_2_FB
  CB_chose_attr <-    input$attributes_target_2_CB
  RE_chose_attr <-    input$attributes_target_2_RE
  RG_chose_attr <-    input$attributes_target_2_RG
  RT_chose_attr <-    input$attributes_target_2_RT
  LE_chose_attr <-    input$attributes_target_2_LE
  LG_chose_attr <-    input$attributes_target_2_LG
  LT_chose_attr <-    input$attributes_target_2_LT
  DT_chose_attr <-    input$attributes_target_2_DT
  LOLB_chose_attr <-  input$attributes_target_2_LOLB
  ROLB_chose_attr <-  input$attributes_target_2_ROLB
  SS_chose_attr <-    input$attributes_target_2_SS
  FS_chose_attr <-    input$attributes_target_2_FS
  TE_chose_attr <-    input$attributes_target_2_TE
  MLB_chose_attr <-   input$attributes_target_2_MLB
  P_chose_attr <-     input$attributes_target_2_P
  K_chose_attr <-     input$attributes_target_2_K
  
  
  # WR_chose_attr <- c("playerBestOvr","speedRating","routeRunShortRating","runBlockFinesseRating","runBlockPowerRating" )
  # QB_chose_attr <- c("playerBestOvr","speedRating")
  # HB_chose_attr <- c("playerBestOvr")
  # FB_chose_attr <- c("playerBestOvr", "elusiveRating", "jukeMoveRating")
  # CB_chose_attr <- c("playerBestOvr","speedRating")
  # RE_chose_attr <- c("playerBestOvr","speedRating")
  # RG_chose_attr <- c("playerBestOvr","speedRating")
  # RT_chose_attr <- c("playerBestOvr","speedRating")
  # LE_chose_attr <- c("playerBestOvr","speedRating")
  # LG_chose_attr <- c("playerBestOvr","speedRating")
  # LT_chose_attr <- c("playerBestOvr","speedRating")
  # DT_chose_attr <- c("playerBestOvr","speedRating")
  # LOLB_chose_attr <- c("playerBestOvr","speedRating")
  # ROLB_chose_attr <- c("playerBestOvr","speedRating")
  # SS_chose_attr <- c("playerBestOvr","speedRating")
  # FS_chose_attr <- c("playerBestOvr","speedRating")
  # TE_chose_attr <- c("playerBestOvr","speedRating")
  # MLB_chose_attr <- c("playerBestOvr","speedRating")
  # C_chose_attr <- c("playerBestOvr","speedRating")
  # P_chose_attr <- c("playerBestOvr","speedRating")
  # K_chose_attr <- c("playerBestOvr","speedRating")
  
  attr_obj <- lst(
    WR_chose_attr ,  
    QB_chose_attr ,  
    C_chose_attr ,   
    HB_chose_attr ,  
    FB_chose_attr ,  
    CB_chose_attr ,  
    RE_chose_attr ,  
    RG_chose_attr ,  
    RT_chose_attr ,  
    LE_chose_attr ,  
    LG_chose_attr ,  
    LT_chose_attr ,  
    DT_chose_attr ,    
    LOLB_chose_attr ,  
    ROLB_chose_attr ,
    SS_chose_attr ,    
    FS_chose_attr ,    
    TE_chose_attr ,    
    MLB_chose_attr , 
    P_chose_attr ,     
    K_chose_attr,
  )
  
  df_attr <- plyr::ldply(attr_obj, rbind)
  df_attr <- gather(data = df_attr, key = key, value = value, na.rm = T, -.id)
  
  df_attr <- 
    df_attr %>% 
    select(-key) %>% 
    rename(key = .id)
  
  df_attr <- df_attr %>% mutate(key = gsub(pattern = "_chose_attr",replacement = "", x = .[["key"]]))
  
  df_attr$use = 1
  
  df_attr <- 
    df_attr %>%
    rename(position = key,
           attribute = value)
  
  df_initial <- 
    player_data_slim_1 %>% 
    # filter(draftRound<56) %>% 
    ungroup() %>% 
    # group_by(position) %>% 
    mutate_if(is.numeric, .funs = standard_mutate) %>% 
    gather(key = "attribute", "value", -id, -team, -firstName, -lastName, -position) %>% 
    left_join(df_attr) %>% 
    filter(use == 1) %>% 
    filter(!is.na(use)) %>% 
    mutate(id = as.character(id)) %>% 
    group_by(id, team, firstName, lastName, position) %>% 
    mutate(value = as.numeric(value)) %>% 
    summarise(value = mean(value, na.rm = T)) %>% 
    arrange(desc(value))
  
  
  player_data_value_2 <- 
    df_initial %>% 
    ungroup() %>% 
    mutate(z_score = standard_mutate(value)) %>% 
    group_by(position) %>% 
    mutate(replacement = quantile(z_score, probs = .5)) %>% 
    mutate(zsar = z_score - replacement) %>% 
    ungroup() %>% 
    left_join(df_adj %>% select(term, adjustment), by = c("position"  = "term")) %>% 
    mutate(zsar_adj = zsar *adjustment) %>% 
    mutate(annual_value_pick = (total_salary/sum(zsar_adj, na.rm = T))*zsar_adj) %>% 
    select(id:position, annual_value_pick)
  
  player_data_value_final_team <- 
    player_data_value %>% left_join(player_data_value_2) %>% 
    mutate(annual_excess_value_pick = annual_value_pick - salary_per_year, 
           total_value_contract_pick = adj_contract_years_left * annual_excess_value_pick) %>% 
    arrange(desc(total_value_contract_pick)) %>% 
    # left_join(draft_position) %>% 
    # mutate(actual_value_pos = rank(desc(total_value_contract_pick))) %>% 
    # mutate(value_pick = -(actual_value_pos-expect_draft_pos)) %>% 
    left_join(required_depth) %>% 
    arrange(desc(total_value_contract_pick)) %>% 
    group_by(team, position) %>% 
    mutate(rank = rank(desc(annual_value_pick), ties.method = "first")) %>% 
    filter(rank <= num) %>%
    summarise(value = round(mean(total_value_contract_pick),0)) %>%
    spread(key = team, value = value, fill = -1000000)
  
  
  DT::datatable(player_data_value_final_team, extensions = c('Buttons','FixedColumns'),
                filter = "top",
                options = list(
                  scrollX = TRUE,
                  pageLength = -1, 
                  scrollY = "600px",
                  fixedColumns = list(leftColumns = 1), 
                  dom = 'Bfrti',
                  buttons = list(
                    list(extend = 'collection',
                         buttons = c('excel', 'csv'),
                         text = 'DOWNLOAD DATA')
                  ))) %>% 
    formatCurrency(columns = unique(player_data$team),
                   digits = 0)
})


```

Team Overview
=====================================  

Sidebar {.sidebar}
-------------------------------------

```{r}
pickerInput(inputId = "team_picks",
            label = "What team do you want to review:",
            choices = unique(player_data$team),
            selected = c("Panthers", "Seahawks", "Patriots", "Bills", "Browns", "Ravens", "Saints", "Football Team"),
            multiple = TRUE,
            options = list(`actions-box` = TRUE)
)



player_data_cut <-
  player_data %>% 
  left_join(required_depth) %>% 
  arrange(desc(playerBestOvr)) %>% 
  group_by(team, position) %>% 
  mutate(rank = rank(-playerBestOvr, ties.method = "first")) %>% 
  filter(rank <= num)

```

Overview Tables  {.tabset .tabset-fade}
-------------------------------------

### Positions

```{r}


renderPlot({
  
  team_picks <- input$team_picks
  # team_picks <- c("Panthers", "Seahawks", "Patriots", "Bills", "Browns", "Ravens", "Saints", "Football Team", "Dolphins")
  
  # player_data_cut %>% 
  #   filter(team %in% team_picks) %>% 
  #   # group_by(team, group_position) %>%
  #   # summarise(rating = mean(playerBestOvr)) %>% 
  #   ggplot(aes(team, playerBestOvr, color = team)) +
  #   geom_boxplot(position='dodge') +
  #   coord_flip()+
  #   # scale_y_continuous(limits=c(60,90),oob = rescale_none)
  #   facet_wrap(~group_position, scales = "free_y", nrow = 1) +
  #   labs(y = "Average Rating of Starters by Position")
  
  player_data_cut %>% 
    filter(team %in% team_picks) %>% 
    mutate(team = as_factor(team)) %>% 
    mutate(group_position = as_factor(group_position)) %>% 
    group_by(team, group_position, .drop = F) %>%
    summarise(rating = mean(playerBestOvr),
              max_rating = max(playerBestOvr),
              min_rating = min(playerBestOvr)) %>%
    # mutate(team = reorder_within(team, rating, group_position)) %>% 
    group_by(group_position) %>% 
    mutate(team = fct_reorder(team, filter(., group_position == "QB") %>% pull(rating))) %>% 
    ungroup() %>% 
    mutate(group_position = fct_relevel(group_position,c("QB","WR","RB","OL","TE","DB","LB","DL","K"))) %>% 
    ggplot(aes(team, rating, ymin=min_rating, ymax=max_rating, 
               group = team,
               color = team)) +
    geom_pointrange()+
    facet_wrap(~group_position, scales = "fixed", nrow = 1) +
    coord_flip()+
    # scale_x_reordered() +
    # scale_y_continuous(limits=c(60,90),oob = rescale_none)
    labs(y = "Average Rating of Starters by Position") +
    theme(legend.position = "none")
  
  
})


```

### 3 Phases

```{r}


renderPlot({
  
  team_picks <- input$team_picks
  # team_picks <- c("Panthers", "Seahawks", "Patriots", "Bills", "Browns", "Ravens", "Saints", "Football Team")
  
  player_data_cut %>% 
    filter(team %in% team_picks) %>% 
    mutate(team = as_factor(team)) %>% 
    mutate(simple_position = as_factor(simple_position)) %>% 
    group_by(team, simple_position, .drop=F) %>%
    summarise(rating = mean(playerBestOvr),
              max_rating = max(playerBestOvr),
              min_rating = min(playerBestOvr)) %>%
    group_by(simple_position) %>% 
    mutate(team = fct_reorder(team, filter(., simple_position == "Offense") %>% pull(rating))) %>% 
    ungroup() %>% 
    mutate(simple_position = fct_relevel(simple_position,c("Offense","Defense","Special_Team"))) %>% 
    ggplot(aes(team, rating, ymin=min_rating, ymax=max_rating, 
               group = team,
               color = team)) +
    geom_pointrange()+
    coord_flip()+
    # scale_y_continuous(limits=c(60,90),oob = rescale_none)
    facet_wrap(~simple_position, scales = "fixed", nrow = 1) +
    labs(y = "Average Rating of Starters by Position")+
    theme(legend.position = "none")
  
})
```

Raw Data
=====================================     

-------------------------------------

### Raw Data

```{r}

DT::renderDataTable({
  
  
  
  DT::datatable(player_data, extensions = c('Buttons','FixedColumns'),
                filter = "top",
                options = list(
                  scrollX = TRUE,
                  pageLength = -1, 
                  scrollY = "600px",
                  fixedColumns = list(leftColumns = 5), 
                  dom = 'Bfrti',
                  buttons = list(
                    list(extend = 'collection',
                         buttons = c('excel', 'csv'),
                         text = 'DOWNLOAD DATA')
                  ))) 
  
})



```

Draft (One Year)
=====================================  

Sidebar {.sidebar}
-------------------------------------

```{r}


selectInput(inputId = "attributes_target_2_QB",
            label = "QB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            # selected = c("playerBestOvr", "youth", "devTrait", "throwAccDeepRating", 
            #              "throwAccMidRating", "throwAccRating", 
            #              "throwAccShortRating", "throwPowerRating", 
            #              "throwUnderPressureRating", "tightSpiralTrait"),
            selected = c("playerBestOvr", "youth", "devTrait", "throwAccShortRating", "throwAccDeepRating", 
                         "throwPowerRating",
                         "throwUnderPressureRating", "tightSpiralTrait"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_WR",
            label = "WR Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "speedRating", "jumpRating", 
                         "accelRating", "releaseRating", "catchRating", "routeRunShortRating", "routeRunDeepRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_TE",
            label = "TE Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "speedRating", "jumpRating", 
                         "accelRating", "releaseRating", "catchRating", "routeRunShortRating", "routeRunDeepRating", "runBlockRating", "passBlockRating",
                         "playRecRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_HB",
            label = "HB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "awareRating", "playRecRating", "bCVRating", "catchRating", "breakTackleRating", "speedRating", "accelRating", "passBlockRating",
                         "carryRating", "strengthRating", "jukeMoveRating", "truckRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_FB",
            label = "FB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "leadBlockRating", "awareRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_LE",
            label = "LE Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr",  "blockShedRating", "dLBullRushTrait",
                         "awareRating", "playRecRating", 
                         "tackleRating", "pursuitRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_RE",
            label = "RE Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr",  "blockShedRating", 
                         "awareRating", "playRecRating", "dLBullRushTrait",
                         "tackleRating", "pursuitRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_DT",
            label = "DT Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr","blockShedRating", "dLBullRushTrait",
                         "awareRating", "playRecRating", 
                         "tackleRating", "pursuitRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_C",
            label = "C Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr",   "awareRating", 
                         "playRecRating","passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_RG",
            label = "RG Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr",  "awareRating", 
                         "playRecRating","passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_LG",
            label = "LG Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr",  "awareRating", 
                         "playRecRating", "passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_RT",
            label = "RT Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr",  "awareRating", 
                         "playRecRating", "passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_LT",
            label = "LT Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "awareRating", 
                         "playRecRating", "passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_LOLB",
            label = "LOLB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected =c("playerBestOvr","awareRating", 
                        "playRecRating", "passBlockFinesseRating",	"passBlockPowerRating",	"passBlockRating","runBlockFinesseRating",	"runBlockPowerRating",	"runBlockRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_ROLB",
            label = "ROLB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "awareRating", 
                         "playRecRating", "speedRating", "accelRating", 
                         "tackleRating", "pursuitRating", "zoneCoverRating", "manCoverRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_MLB",
            label = "MLB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "awareRating", "playRecRating", 
                         "speedRating", "accelRating", 
                         "tackleRating", "pursuitRating", "zoneCoverRating", "changeOfDirectionRating", "zoneCoverRating", "manCoverRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_CB",
            label = "CB Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "awareRating", "playRecRating", 
                         "speedRating", "accelRating", "agility",
                         "manCoverRating", "catchRating", "playBallTrait", "zoneCoverRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_SS",
            label = "SS Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr",  "awareRating", "playRecRating", 
                         "speedRating", "accelRating", 
                         "tackleRating", "pursuitRating", "zoneCoverRating",  "manCoverRating",
                         "catchRating", "playBallTrait", "changeOfDirectionRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_FS",
            label = "FS Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("playerBestOvr", "awareRating", "playRecRating", 
                         "speedRating", "accelRating",   "manCoverRating",
                         "tackleRating", "pursuitRating", "zoneCoverRating", "catchRating", "playBallTrait",
                         "changeOfDirectionRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_P",
            label = "P Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("kickAccRating", "kickPowerRating"),
            multiple = TRUE
)

selectInput(inputId = "attributes_target_2_K",
            label = "K Desired Attributes:",
            choices = names(player_data %>% select(-teamId,-firstName, -team,  -lastName,-position)),
            selected = c("kickAccRating", "kickPowerRating"),
            multiple = TRUE
)



df_adj <- structure(list(term = c("LOLB", "LT", "LE", "DT", "SS", "MLB", 
                                  "K", "RG", "TE", "ROLB", "LG", "WR", "FS", "CB", "HB", "P", "QB", 
                                  "RE", "RT", "C", "FB"), adjustment = c(0.862629912479771, 0.90910023267521, 
                                                                         0.929600934318827, 0.857455750288059, 0.804422695726924, 0.916405774674934, 
                                                                         0.399402386037169, 0.823656929607914, 0.810042189930614, 0.900599462830276, 
                                                                         0.852989137742854, 0.875878186217941, 0.858236691240959, 0.952873137803954, 
                                                                         0.818204105395157, 0.451785887708866, 1, 0.894419724590175, 0.886991503780299, 
                                                                         0.837555614337102, 0.745367603657523)), row.names = c(NA, -21L
                                                                         ), class = c("tbl_df", "tbl", "data.frame"))

#Came From This Code in a separate analysis
# cores <- parallel::detectCores()
# 
# player_data_numeric <- 
#   player_data_slim %>% 
#   # filter(position == i) %>% 
#   select_if(is.numeric) 
# 
# player_data_logic <- 
#   player_data_slim %>% 
#   # filter(position == i) %>% 
#   select_if(is.logical) %>%
#   mutate_if(is.logical, as.integer)
# 
# player_data_data_first <- 
#   player_data_slim %>% select(team:position) %>%  
#   cbind(player_data_numeric) %>% 
#   cbind(player_data_logic) %>% 
#   filter(yearsPro>4) %>%  
#   filter(yearsPro<8) %>%  
#   mutate(salary_per_year = contractSalary/contractLength) %>% 
#   filter(!is.na(salary_per_year)) %>% 
#   select(id, team, firstName, lastName, contractYearsLeft, salary_per_year, position , playerBestOvr, devTrait) 
# 
# player_data_data <- 
#   player_data_data_first %>% 
#   pivot_wider(names_from = "position", values_from = "playerBestOvr")
# 
# summary <- 
# player_data_data_first %>% 
#   mutate(player_type = ifelse((playerBestOvr>66) & (playerBestOvr<74), "low_player", NA)) %>% 
#   mutate(player_type = ifelse((playerBestOvr>76) & (playerBestOvr<84), "high_player", player_type)) %>% 
#   filter(!is.na(player_type)) %>% 
#   group_by(position, player_type) %>% 
#   summarise(salary_per_year = mean(salary_per_year)) %>% 
#   pivot_wider(names_from = "player_type", values_from = salary_per_year) %>% 
#   mutate(cost_per_pt = (high_player - low_player)/10)
#   
# 
# player_data_data[is.na(player_data_data)] <- 0
# 
# set.seed(123)
# splits      <- initial_split(player_data_data, strata = salary_per_year, prop = .90)
# 
# player_other <- training(splits)
# player_test  <- testing(splits)
# 
# set.seed(345)
# folds <- vfold_cv(player_other, v = 3)
# folds
# 
# # cores <- pmin(cores, 10)
# 
# model <-
#     linear_reg() %>%
#     set_mode("regression") %>%
#     set_engine("lm")
# 
# recipe <- 
#   recipe(salary_per_year ~ ., data = player_other) %>% 
#   # step_ns(playerBestOvr, deg_free = 2) %>%  #, 
#   update_role(id, team, firstName, lastName, contractYearsLeft, new_role = "ID") %>%
#   step_mutate(devTrait = as.factor(devTrait))
#   # step_dummy(position) #, devTrait) 
#  
# workflow <- 
#   workflow() %>% 
#   add_model(model) %>% 
#   add_recipe(recipe)
# 
# final_fit <- 
#   workflow %>%
#   fit(data = player_other) 
# 
# library(broom)
# df_adj <- tidy(final_fit$fit$fit)
# 
# df_adj$adjustment <- df_adj$estimate / (df_adj$estimate[df_adj$term=="QB"])
# 
# df_adj


player_data_slim_1 <- 
  player_data %>% 
  # filter(draftRound<56) %>% 
  mutate(salary_per_year = contractSalary/contractLength) %>% 
  mutate(id = as.character(id))

total_salary <- sum(player_data_slim_1$salary_per_year, na.rm = T)/2

player_data_value <- 
  player_data_slim_1 %>% 
  mutate(z_score = standard_mutate(playerBestOvr)) %>% 
  group_by(position) %>% 
  mutate(replacement = quantile(z_score, probs = .55)) %>% 
  mutate(zsar = z_score - replacement) %>% 
  mutate(salary_per_year = contractSalary/contractLength) %>% 
  ungroup() %>% 
  left_join(df_adj %>% select(term, adjustment), by = c("position"  = "term")) %>% 
  mutate(zsar_adj = zsar *adjustment) %>% 
  mutate(annual_value = round((total_salary/sum(zsar_adj, na.rm = T))*zsar_adj,0)) %>% 
  mutate(annual_excess_value = annual_value - salary_per_year) %>% 
  select(id, team, firstName, lastName, position, age, yearsPro, draftPick, draftRound, playerBestOvr, devTrait, 
         z_score, replacement, zsar, adjustment, zsar_adj,
         salary_per_year, contractYearsLeft,
         annual_value, annual_excess_value) %>% 
  mutate(adj_contract_years_left = 1) %>% 
  mutate(total_value_contract = adj_contract_years_left * annual_excess_value) %>% 
  arrange(desc(total_value_contract))

##Expected Draft position
# draft_position <- 
#   player_data %>% 
#   filter(draftRound<56) %>% 
#   select(id, draftPick, draftRound) %>% 
#   mutate(expect_draft_pos = (draftRound-2)*32+(draftPick - 1),
#          id = as.character(id)) %>% 
#   select(-draftPick, -draftRound)


```

Draft Tables  {.tabset .tabset-fade}
-------------------------------------

### Draft Individual

```{r eval=T}


DT::renderDataTable({
  
  WR_chose_attr <-    input$attributes_target_2_WR
  QB_chose_attr <-    input$attributes_target_2_QB
  C_chose_attr <-     input$attributes_target_2_C
  HB_chose_attr <-    input$attributes_target_2_HB
  FB_chose_attr <-    input$attributes_target_2_FB
  CB_chose_attr <-    input$attributes_target_2_CB
  RE_chose_attr <-    input$attributes_target_2_RE
  RG_chose_attr <-    input$attributes_target_2_RG
  RT_chose_attr <-    input$attributes_target_2_RT
  LE_chose_attr <-    input$attributes_target_2_LE
  LG_chose_attr <-    input$attributes_target_2_LG
  LT_chose_attr <-    input$attributes_target_2_LT
  DT_chose_attr <-    input$attributes_target_2_DT
  LOLB_chose_attr <-  input$attributes_target_2_LOLB
  ROLB_chose_attr <-  input$attributes_target_2_ROLB
  SS_chose_attr <-    input$attributes_target_2_SS
  FS_chose_attr <-    input$attributes_target_2_FS
  TE_chose_attr <-    input$attributes_target_2_TE
  MLB_chose_attr <-   input$attributes_target_2_MLB
  P_chose_attr <-     input$attributes_target_2_P
  K_chose_attr <-     input$attributes_target_2_K
  
  # 
  #   WR_chose_attr <- c("playerBestOvr","speedRating","routeRunShortRating","runBlockFinesseRating","runBlockPowerRating" )
  #   QB_chose_attr <- c("playerBestOvr","speedRating")
  #   HB_chose_attr <- c("playerBestOvr")
  #   FB_chose_attr <- c("playerBestOvr", "elusiveRating", "jukeMoveRating")
  #   CB_chose_attr <- c("playerBestOvr","speedRating")
  #   RE_chose_attr <- c("playerBestOvr","speedRating")
  #   RG_chose_attr <- c("playerBestOvr","speedRating")
  #   RT_chose_attr <- c("playerBestOvr","speedRating")
  #   LE_chose_attr <- c("playerBestOvr","speedRating")
  #   LG_chose_attr <- c("playerBestOvr","speedRating")
  #   LT_chose_attr <- c("playerBestOvr","speedRating")
  #   DT_chose_attr <- c("playerBestOvr","speedRating")
  #   LOLB_chose_attr <- c("playerBestOvr","speedRating")
  #   ROLB_chose_attr <- c("playerBestOvr","speedRating")
  #   SS_chose_attr <- c("playerBestOvr","speedRating")
  #   FS_chose_attr <- c("playerBestOvr","speedRating")
  #   TE_chose_attr <- c("playerBestOvr","speedRating")
  #   MLB_chose_attr <- c("playerBestOvr","speedRating")
  #   C_chose_attr <- c("playerBestOvr","speedRating")
  #   P_chose_attr <- c("playerBestOvr","speedRating")
  #   K_chose_attr <- c("playerBestOvr","speedRating")
  
  attr_obj <- lst(
    WR_chose_attr ,  
    QB_chose_attr ,  
    C_chose_attr ,   
    HB_chose_attr ,  
    FB_chose_attr ,  
    CB_chose_attr ,  
    RE_chose_attr ,  
    RG_chose_attr ,  
    RT_chose_attr ,  
    LE_chose_attr ,  
    LG_chose_attr ,  
    LT_chose_attr ,  
    DT_chose_attr ,    
    LOLB_chose_attr ,  
    ROLB_chose_attr ,
    SS_chose_attr ,    
    FS_chose_attr ,    
    TE_chose_attr ,    
    MLB_chose_attr , 
    P_chose_attr ,     
    K_chose_attr,
  )
  
  df_attr <- plyr::ldply(attr_obj, rbind)
  df_attr <- gather(data = df_attr, key = key, value = value, na.rm = T, -.id)
  
  df_attr <- 
    df_attr %>% 
    select(-key) %>% 
    rename(key = .id)
  
  df_attr <- df_attr %>% mutate(key = gsub(pattern = "_chose_attr",replacement = "", x = .[["key"]]))
  
  df_attr$use = 1
  
  df_attr <- 
    df_attr %>%
    rename(position = key,
           attribute = value)
  
  df_initial <- 
    player_data_slim_1 %>% 
    # filter(draftRound<56) %>% 
    ungroup() %>% 
    # group_by(position) %>% 
    mutate_if(is.numeric, .funs = standard_mutate) %>% 
    gather(key = "attribute", "value", -id, -team, -firstName, -lastName, -position) %>% 
    left_join(df_attr) %>% 
    filter(use == 1) %>% 
    filter(!is.na(use)) %>% 
    mutate(id = as.character(id)) %>% 
    group_by(id, team, firstName, lastName, position) %>% 
    mutate(value = round(as.numeric(value),3)) %>% 
    summarise(value = round(mean(value, na.rm = T),3)) %>% 
    arrange(desc(value))
  
  
  player_data_value_2 <- 
    df_initial %>% 
    ungroup() %>% 
    mutate(z_score_2 = standard_mutate(value)) %>% 
    group_by(position) %>% 
    mutate(replacement_2 = quantile(z_score_2, probs = .5)) %>% 
    mutate(zsar_2 = z_score_2 - replacement_2) %>% 
    ungroup() %>% 
    left_join(df_adj %>% select(term, adjustment), by = c("position"  = "term")) %>% 
    mutate(zsar_adj_2 = zsar_2 *adjustment) %>% 
    mutate(annual_value_pick = round((total_salary/sum(zsar_adj_2, na.rm = T))*zsar_adj_2,0)) %>% 
    select(id:position, z_score_2, zsar_2, zsar_adj_2, annual_value_pick)
  
  player_data_value_final <- 
    player_data_value %>% left_join(player_data_value_2) %>% 
    mutate(annual_excess_value_pick = round(annual_value_pick - salary_per_year,0), 
           total_value_contract_pick = adj_contract_years_left * annual_excess_value_pick) %>% 
    arrange(desc(total_value_contract_pick))# %>% 
  # left_join(draft_position) %>% 
  # mutate(actual_value_pos = rank(desc(total_value_contract_pick))) %>% 
  # mutate(value_pick = -(actual_value_pos-expect_draft_pos))
  
  
  DT::datatable(player_data_value_final, extensions = c('Buttons','FixedColumns'),
                filter = "top",
                options = list(
                  scrollX = TRUE,
                  pageLength = -1, 
                  scrollY = "600px",
                  fixedColumns = list(leftColumns = 5), 
                  dom = 'Bfrti',
                  buttons = list(
                    list(extend = 'collection',
                         buttons = c('excel', 'csv'),
                         text = 'DOWNLOAD DATA')
                  ))) 
})


```


### Draft Team

```{r eval=T}


DT::renderDataTable({
  
  WR_chose_attr <-    input$attributes_target_2_WR
  QB_chose_attr <-    input$attributes_target_2_QB
  C_chose_attr <-     input$attributes_target_2_C
  HB_chose_attr <-    input$attributes_target_2_HB
  FB_chose_attr <-    input$attributes_target_2_FB
  CB_chose_attr <-    input$attributes_target_2_CB
  RE_chose_attr <-    input$attributes_target_2_RE
  RG_chose_attr <-    input$attributes_target_2_RG
  RT_chose_attr <-    input$attributes_target_2_RT
  LE_chose_attr <-    input$attributes_target_2_LE
  LG_chose_attr <-    input$attributes_target_2_LG
  LT_chose_attr <-    input$attributes_target_2_LT
  DT_chose_attr <-    input$attributes_target_2_DT
  LOLB_chose_attr <-  input$attributes_target_2_LOLB
  ROLB_chose_attr <-  input$attributes_target_2_ROLB
  SS_chose_attr <-    input$attributes_target_2_SS
  FS_chose_attr <-    input$attributes_target_2_FS
  TE_chose_attr <-    input$attributes_target_2_TE
  MLB_chose_attr <-   input$attributes_target_2_MLB
  P_chose_attr <-     input$attributes_target_2_P
  K_chose_attr <-     input$attributes_target_2_K
  
  
  # WR_chose_attr <- c("playerBestOvr","speedRating","routeRunShortRating","runBlockFinesseRating","runBlockPowerRating" )
  # QB_chose_attr <- c("playerBestOvr","speedRating")
  # HB_chose_attr <- c("playerBestOvr")
  # FB_chose_attr <- c("playerBestOvr", "elusiveRating", "jukeMoveRating")
  # CB_chose_attr <- c("playerBestOvr","speedRating")
  # RE_chose_attr <- c("playerBestOvr","speedRating")
  # RG_chose_attr <- c("playerBestOvr","speedRating")
  # RT_chose_attr <- c("playerBestOvr","speedRating")
  # LE_chose_attr <- c("playerBestOvr","speedRating")
  # LG_chose_attr <- c("playerBestOvr","speedRating")
  # LT_chose_attr <- c("playerBestOvr","speedRating")
  # DT_chose_attr <- c("playerBestOvr","speedRating")
  # LOLB_chose_attr <- c("playerBestOvr","speedRating")
  # ROLB_chose_attr <- c("playerBestOvr","speedRating")
  # SS_chose_attr <- c("playerBestOvr","speedRating")
  # FS_chose_attr <- c("playerBestOvr","speedRating")
  # TE_chose_attr <- c("playerBestOvr","speedRating")
  # MLB_chose_attr <- c("playerBestOvr","speedRating")
  # C_chose_attr <- c("playerBestOvr","speedRating")
  # P_chose_attr <- c("playerBestOvr","speedRating")
  # K_chose_attr <- c("playerBestOvr","speedRating")
  
  attr_obj <- lst(
    WR_chose_attr ,  
    QB_chose_attr ,  
    C_chose_attr ,   
    HB_chose_attr ,  
    FB_chose_attr ,  
    CB_chose_attr ,  
    RE_chose_attr ,  
    RG_chose_attr ,  
    RT_chose_attr ,  
    LE_chose_attr ,  
    LG_chose_attr ,  
    LT_chose_attr ,  
    DT_chose_attr ,    
    LOLB_chose_attr ,  
    ROLB_chose_attr ,
    SS_chose_attr ,    
    FS_chose_attr ,    
    TE_chose_attr ,    
    MLB_chose_attr , 
    P_chose_attr ,     
    K_chose_attr,
  )
  
  df_attr <- plyr::ldply(attr_obj, rbind)
  df_attr <- gather(data = df_attr, key = key, value = value, na.rm = T, -.id)
  
  df_attr <- 
    df_attr %>% 
    select(-key) %>% 
    rename(key = .id)
  
  df_attr <- df_attr %>% mutate(key = gsub(pattern = "_chose_attr",replacement = "", x = .[["key"]]))
  
  df_attr$use = 1
  
  df_attr <- 
    df_attr %>%
    rename(position = key,
           attribute = value)
  
  df_initial <- 
    player_data_slim_1 %>% 
    # filter(draftRound<56) %>% 
    ungroup() %>% 
    # group_by(position) %>% 
    mutate_if(is.numeric, .funs = standard_mutate) %>% 
    gather(key = "attribute", "value", -id, -team, -firstName, -lastName, -position) %>% 
    left_join(df_attr) %>% 
    filter(use == 1) %>% 
    filter(!is.na(use)) %>% 
    mutate(id = as.character(id)) %>% 
    group_by(id, team, firstName, lastName, position) %>% 
    mutate(value = as.numeric(value)) %>% 
    summarise(value = mean(value, na.rm = T)) %>% 
    arrange(desc(value))
  
  
  player_data_value_2 <- 
    df_initial %>% 
    ungroup() %>% 
    mutate(z_score = standard_mutate(value)) %>% 
    group_by(position) %>% 
    mutate(replacement = quantile(z_score, probs = .5)) %>% 
    mutate(zsar = z_score - replacement) %>% 
    ungroup() %>% 
    left_join(df_adj %>% select(term, adjustment), by = c("position"  = "term")) %>% 
    mutate(zsar_adj = zsar *adjustment) %>% 
    mutate(annual_value_pick = (total_salary/sum(zsar_adj, na.rm = T))*zsar_adj) %>% 
    select(id:position, annual_value_pick)
  
  player_data_value_final_team <- 
    player_data_value %>% left_join(player_data_value_2) %>% 
    mutate(annual_excess_value_pick = annual_value_pick - salary_per_year, 
           total_value_contract_pick = adj_contract_years_left * annual_excess_value_pick) %>% 
    arrange(desc(total_value_contract_pick)) %>% 
    # left_join(draft_position) %>% 
    # mutate(actual_value_pos = rank(desc(total_value_contract_pick))) %>% 
    # mutate(value_pick = -(actual_value_pos-expect_draft_pos)) %>% 
    left_join(required_depth) %>% 
    arrange(desc(total_value_contract_pick)) %>% 
    group_by(team, position) %>% 
    mutate(rank = rank(desc(annual_value_pick), ties.method = "first")) %>% 
    filter(rank <= num) %>%
    summarise(value = round(mean(total_value_contract_pick),0)) %>%
    spread(key = position, value = value, fill = -1000000) %>%
    mutate(Total = C+ CB+ DT+ FS+ HB+ K+ LE+ LG+ LOLB+ LT+ MLB+ P+ QB+ RE+ RG+ ROLB+ RT+ SS+ TE+ WR) %>%
    mutate(Brent_Total = (1*C+ 2*CB+ 2*DT+ 2*FS+ 1*HB+ .5*K+ 2*LE+ 
                            1*LG+ 2*LOLB+ 1*LT+ 1*MLB+ .5*P+ 2*QB+ 2*RE+ 1*RG+ 
                            2*ROLB+ 1*RT+ 2*SS+ 1*TE+ 2*WR)/
             sum(1,2,2,2,1,.5,2,1,2,1,1,.5,2,2,1,2,1,2,2,2)
           
    ) %>%
    arrange(desc(Brent_Total))
  
  
  DT::datatable(player_data_value_final_team, extensions = c('Buttons','FixedColumns'),
                filter = "top",
                options = list(
                  scrollX = TRUE,
                  pageLength = -1, 
                  scrollY = "600px",
                  fixedColumns = list(leftColumns = 1), 
                  dom = 'Bfrti',
                  buttons = list(
                    list(extend = 'collection',
                         buttons = c('excel', 'csv'),
                         text = 'DOWNLOAD DATA')
                  ))) %>% 
    formatCurrency(columns = ~C+ CB+ DT+ FS+ HB+ K+ LE+ LG+ LOLB+ LT+ MLB+ P+ QB+ RE+ RG+ ROLB+ RT+ SS+ TE+ WR + Total+Brent_Total,
                   digits = 0)
})


```

### Draft Team (Tranpose)

```{r eval=T}


DT::renderDataTable({
  
  WR_chose_attr <-    input$attributes_target_2_WR
  QB_chose_attr <-    input$attributes_target_2_QB
  C_chose_attr <-     input$attributes_target_2_C
  HB_chose_attr <-    input$attributes_target_2_HB
  FB_chose_attr <-    input$attributes_target_2_FB
  CB_chose_attr <-    input$attributes_target_2_CB
  RE_chose_attr <-    input$attributes_target_2_RE
  RG_chose_attr <-    input$attributes_target_2_RG
  RT_chose_attr <-    input$attributes_target_2_RT
  LE_chose_attr <-    input$attributes_target_2_LE
  LG_chose_attr <-    input$attributes_target_2_LG
  LT_chose_attr <-    input$attributes_target_2_LT
  DT_chose_attr <-    input$attributes_target_2_DT
  LOLB_chose_attr <-  input$attributes_target_2_LOLB
  ROLB_chose_attr <-  input$attributes_target_2_ROLB
  SS_chose_attr <-    input$attributes_target_2_SS
  FS_chose_attr <-    input$attributes_target_2_FS
  TE_chose_attr <-    input$attributes_target_2_TE
  MLB_chose_attr <-   input$attributes_target_2_MLB
  P_chose_attr <-     input$attributes_target_2_P
  K_chose_attr <-     input$attributes_target_2_K
  
  
  # WR_chose_attr <- c("playerBestOvr","speedRating","routeRunShortRating","runBlockFinesseRating","runBlockPowerRating" )
  # QB_chose_attr <- c("playerBestOvr","speedRating")
  # HB_chose_attr <- c("playerBestOvr")
  # FB_chose_attr <- c("playerBestOvr", "elusiveRating", "jukeMoveRating")
  # CB_chose_attr <- c("playerBestOvr","speedRating")
  # RE_chose_attr <- c("playerBestOvr","speedRating")
  # RG_chose_attr <- c("playerBestOvr","speedRating")
  # RT_chose_attr <- c("playerBestOvr","speedRating")
  # LE_chose_attr <- c("playerBestOvr","speedRating")
  # LG_chose_attr <- c("playerBestOvr","speedRating")
  # LT_chose_attr <- c("playerBestOvr","speedRating")
  # DT_chose_attr <- c("playerBestOvr","speedRating")
  # LOLB_chose_attr <- c("playerBestOvr","speedRating")
  # ROLB_chose_attr <- c("playerBestOvr","speedRating")
  # SS_chose_attr <- c("playerBestOvr","speedRating")
  # FS_chose_attr <- c("playerBestOvr","speedRating")
  # TE_chose_attr <- c("playerBestOvr","speedRating")
  # MLB_chose_attr <- c("playerBestOvr","speedRating")
  # C_chose_attr <- c("playerBestOvr","speedRating")
  # P_chose_attr <- c("playerBestOvr","speedRating")
  # K_chose_attr <- c("playerBestOvr","speedRating")
  
  attr_obj <- lst(
    WR_chose_attr ,  
    QB_chose_attr ,  
    C_chose_attr ,   
    HB_chose_attr ,  
    FB_chose_attr ,  
    CB_chose_attr ,  
    RE_chose_attr ,  
    RG_chose_attr ,  
    RT_chose_attr ,  
    LE_chose_attr ,  
    LG_chose_attr ,  
    LT_chose_attr ,  
    DT_chose_attr ,    
    LOLB_chose_attr ,  
    ROLB_chose_attr ,
    SS_chose_attr ,    
    FS_chose_attr ,    
    TE_chose_attr ,    
    MLB_chose_attr , 
    P_chose_attr ,     
    K_chose_attr,
  )
  
  df_attr <- plyr::ldply(attr_obj, rbind)
  df_attr <- gather(data = df_attr, key = key, value = value, na.rm = T, -.id)
  
  df_attr <- 
    df_attr %>% 
    select(-key) %>% 
    rename(key = .id)
  
  df_attr <- df_attr %>% mutate(key = gsub(pattern = "_chose_attr",replacement = "", x = .[["key"]]))
  
  df_attr$use = 1
  
  df_attr <- 
    df_attr %>%
    rename(position = key,
           attribute = value)
  
  df_initial <- 
    player_data_slim_1 %>% 
    # filter(draftRound<56) %>% 
    ungroup() %>% 
    # group_by(position) %>% 
    mutate_if(is.numeric, .funs = standard_mutate) %>% 
    gather(key = "attribute", "value", -id, -team, -firstName, -lastName, -position) %>% 
    left_join(df_attr) %>% 
    filter(use == 1) %>% 
    filter(!is.na(use)) %>% 
    mutate(id = as.character(id)) %>% 
    group_by(id, team, firstName, lastName, position) %>% 
    mutate(value = as.numeric(value)) %>% 
    summarise(value = mean(value, na.rm = T)) %>% 
    arrange(desc(value))
  
  
  player_data_value_2 <- 
    df_initial %>% 
    ungroup() %>% 
    mutate(z_score = standard_mutate(value)) %>% 
    group_by(position) %>% 
    mutate(replacement = quantile(z_score, probs = .5)) %>% 
    mutate(zsar = z_score - replacement) %>% 
    ungroup() %>% 
    left_join(df_adj %>% select(term, adjustment), by = c("position"  = "term")) %>% 
    mutate(zsar_adj = zsar *adjustment) %>% 
    mutate(annual_value_pick = (total_salary/sum(zsar_adj, na.rm = T))*zsar_adj) %>% 
    select(id:position, annual_value_pick)
  
  player_data_value_final_team <- 
    player_data_value %>% left_join(player_data_value_2) %>% 
    mutate(annual_excess_value_pick = annual_value_pick - salary_per_year, 
           total_value_contract_pick = adj_contract_years_left * annual_excess_value_pick) %>% 
    arrange(desc(total_value_contract_pick)) %>% 
    # left_join(draft_position) %>% 
    # mutate(actual_value_pos = rank(desc(total_value_contract_pick))) %>% 
    # mutate(value_pick = -(actual_value_pos-expect_draft_pos)) %>% 
    left_join(required_depth) %>% 
    arrange(desc(total_value_contract_pick)) %>% 
    group_by(team, position) %>% 
    mutate(rank = rank(desc(annual_value_pick), ties.method = "first")) %>% 
    filter(rank <= num) %>%
    summarise(value = round(mean(total_value_contract_pick),0)) %>%
    spread(key = team, value = value, fill = -1000000)
  
  
  DT::datatable(player_data_value_final_team, extensions = c('Buttons','FixedColumns'),
                filter = "top",
                options = list(
                  scrollX = TRUE,
                  pageLength = -1, 
                  scrollY = "600px",
                  fixedColumns = list(leftColumns = 1), 
                  dom = 'Bfrti',
                  buttons = list(
                    list(extend = 'collection',
                         buttons = c('excel', 'csv'),
                         text = 'DOWNLOAD DATA')
                  ))) %>% 
    formatCurrency(columns = unique(player_data$team),
                   digits = 0)
})


```

Team Overview
=====================================  

Sidebar {.sidebar}
-------------------------------------

```{r}
pickerInput(inputId = "team_picks",
            label = "What team do you want to review:",
            choices = unique(player_data$team),
            selected = c("Panthers", "Seahawks", "Patriots", "Bills", "Browns", "Ravens", "Saints", "Football Team"),
            multiple = TRUE,
            options = list(`actions-box` = TRUE)
)



player_data_cut <-
  player_data %>% 
  left_join(required_depth) %>% 
  arrange(desc(playerBestOvr)) %>% 
  group_by(team, position) %>% 
  mutate(rank = rank(-playerBestOvr, ties.method = "first")) %>% 
  filter(rank <= num)

```


